source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

project 'Cell-Rx'
use_frameworks!

target 'Cell-Rx_Example' do
  pod 'Cell+Rx', :path => '../'
  pod 'RxCocoa',    '~> 4.0'
end

target 'Cell-Rx_Tests' do
  pod 'Cell+Rx', :path => '../'
end
